var structmod__class__abstract__parallel__processed__data_1_1class__abstract__parallel__processed__data =
[
    [ "compute_concurrent", "structmod__class__abstract__parallel__processed__data_1_1class__abstract__parallel__processed__data.html#a12f58aa50febe0d7a6625615bad45f7b", null ]
];